[package]
name = "boot-shell"
version = "0.0.1"
edition = "2021"

[lib]
name = "bootshell"
crate-type = ["rlib", "cdylib"]

[dependencies]
serde.workspace = true
serde_json.workspace = true
vib-api.workspace = true

[dev-dependencies]
tempfile.workspace = true

